sidebar:
    left:
        sticky: true
    right:
        sticky: true
widgets:
    -
        position: left
        sticky: true
        type: profile
        author: YttrWillow 的小站
        author_title: みんな、今日も頑張ろう！
        avatar: https://avatars.githubusercontent.com/u/70789009
        avatar_rounded: true
    -
        position: left
        sticky: true
        type: tags
        order_by: name
        amount: 10
        show_count: true
    -
        position: left
        sticky: true
        type: toc
        index: true
        collapsed: true
        depth: 3